name: fluttercharts
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  fl_chart: ^0.70.2
  syncfusion_flutter_charts: ^28.2.3
  flutter_charts: ^0.5.2
  flutter_plot: ^0.1.0
  fl_animated_linechart: ^1.2.0
  flutter_echarts: ^2.5.0
  responsive_framework: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true




